### ISSUE TITLE
[Feature Request] Is there a plan for inline spoiler text and add a switch to it?

### ISSUE THREAD

**Issue by ChangeHow** [AllJavi/spoiler-block-obsidian#3]
Hi,

I just downloaded this plugin and it's amazing!

I just want to know if you already have a plan to support inline spoiler text or provide a switch button that users can click to show/hide the content.

If you don't have time, perhaps I can create a PR to implement these features.

**Comment by jesuslencina** [comment]
Hey! Not a developer of this plugin, but I've made the following custom CSS snippet for inline blurring:

```css
.sensitive {
    transition: filter 1s ease-in-out;
    filter: blur(4px);
    cursor: context-menu;
}

.sensitive:hover{
    filter: blur(0px);
}
```

After this, you can use something like `<span class="sensitive">👀😲🫢</span>` in your text, which will act like this:

![Video_1717439339](https://github.com/AllJavi/spoiler-block-obsidian/assets/36510164/7bc87e1f-ff47-4831-b5fd-8dabe68ba3c4)


Of course, you need to be hovering over the blurred text to see it. You can also make a template out of it if it's annoying to switch to the html mode frequently.

This is just enough for me, feel free to use if it works for you too :)
